name: ${project.name}
main: fr.moribus.imageonmap.ImageOnMap
version: '${minecraft.plugin.version}'
load: POSTWORLD
description: ${project.description}
commands:
   tomap:
      description: render an image in a map
      usage: /<command> [URL]
   maptool:
      description: manage maps
      usage: /<command>
permissions:
    imageonmap.userender:
        description: Allows you to use /tomap
        default: op